# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
zstyle ':omz:update' mode auto
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Aliases
source ~/.aliases

# Make prompt display only the last two directories of cwd
prompt_dir() {
  # !!! BOOTSTRAP_RESOLVE_BEGIN: PROMPT_DIR_COLOR; suggested=214 !!!
  prompt_segment 214 $CURRENT_FG '%2~'
  # !!! BOOTSTRAP_RESOLVE_END: PROMPT_DIR_COLOR !!!
}

# !!! BOOTSTRAP_RESOLVE_BEGIN: DISPLAY !!!
export DISPLAY=:0
# !!! BOOTSTRAP_RESOLVE_END: DISPLAY !!!
export PATH="$HOME/.local/bin:$PATH"

# Remove the snake icon from conda env prefix
prompt_virtualenv() {
  if [ -n "$CONDA_DEFAULT_ENV" ]; then
    prompt_segment magenta $CURRENT_FG "$CONDA_DEFAULT_ENV"
  fi
  if [[ -n "$VIRTUAL_ENV" && -n "$VIRTUAL_ENV_DISABLE_PROMPT" ]]; then
    prompt_segment "$AGNOSTER_VENV_BG" "$AGNOSTER_VENV_FG" "(${VIRTUAL_ENV:t:gs/%/%%})"
  fi
}

source ${ZSH_CUSTOM:-$ZSH/custom}/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${ZSH_CUSTOM:-$ZSH/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
