#!/bin/bash
#SBATCH -J reserved
# !!! BOOTSTRAP_RESOLVE_BEGIN: SLURM_PARTITION !!!
#SBATCH -p <SLURM_PARTITION>
# !!! BOOTSTRAP_RESOLVE_END: SLURM_PARTITION !!!
# !!! BOOTSTRAP_RESOLVE_BEGIN: SLURM_GPU_NAME !!!
#SBATCH --gres=gpu:<SLURM_GPU_NAME>:1
# !!! BOOTSTRAP_RESOLVE_END: SLURM_GPU_NAME !!!
#SBATCH --ntasks=1
# !!! BOOTSTRAP_RESOLVE_BEGIN: SLURM_CPUS_PER_TASK !!!
#SBATCH --cpus-per-task=<SLURM_CPUS_PER_TASK>
# !!! BOOTSTRAP_RESOLVE_END: SLURM_CPUS_PER_TASK !!!
# !!! BOOTSTRAP_RESOLVE_BEGIN: SLURM_MEMORY !!!
#SBATCH --mem=<SLURM_MEMORY>
# !!! BOOTSTRAP_RESOLVE_END: SLURM_MEMORY !!!
# !!! BOOTSTRAP_RESOLVE_BEGIN: SLURM_TIME_LIMIT !!!
#SBATCH --time=<SLURM_TIME_LIMIT>
# !!! BOOTSTRAP_RESOLVE_END: SLURM_TIME_LIMIT !!!
#SBATCH --get-user-env
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err

sleep infinity
